# warm -up

In [42]:

numbers = [0,1,2,3,4,5,6,7,8,9]
rev_num = numbers[::-1]
rev_num

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [45]:
list_com = [number/2 for number in rev_num]
list_com

[4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0.5, 0.0]

In [52]:
def countdown(n):
    
    #count backwards from n until we get to 0
    if n>0:
        #stuff
        countdown(n-1)
        print(n)
    else:
        return #stopping condition - terminates the recursion

In [53]:
countdown(7)

1
2
3
4
5
6
7

In [61]:
A = [2,4,3]
B = [6,5,1]
dotProduct = 0
for i in range(len(A)):
    value = A[i] * B[i]
    dotProduct+=value
    print(dotProduct)

12
32
35

# 1. Write a function that calculates the dot product manually AND a function that
# calculates the cross product manually. Both should accept two vectors and perform
# that calculation. Be sure to use try except and error handling for basic issues that
# might occur.

In [82]:
def dot_product(a,b): 
        summed = 0
        try:
            for i in range(len(a)) and range(len(b)):
                summed = summed +(a[i] * b[i])
        except IndexError:
            print("list must be same size")
        except Exception as e:
            return e
        return summed 
    
    
dot_product([2,2],[2,2])

8

In [ ]:
def cross_product(a,b):

# 2. In a markdown section in your notebook, explain what one hot encoding is and why we
# use it. Then, manually calculate a one hot encoding for the Belize_Airbnb_listings.csv
# neighborhood_group column. Note: manually means donâ€™t use scikitlearn or keras

In [ ]:
Most machine learning tutorials and tools require you to prepare data before it can be fit to a particular ML model. One hot encoding is a process of converting categorical data variables so they can be provided to machine learning algorithms to improve predictions. One hot encoding is a crucial part of feature engineering for machine learning.

In [26]:
import pandas as pd
import numpy as np
from scipy import stats
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats 
file_to_load = "belize_airbnb_listings.csv"
df = pd.read_csv(file_to_load)
df1 = pd.DataFrame(df)
df1

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,36666,Mo's Cozy Casa w/ veranda & access to dock,157752,Monique,Belize,Belize Islands,17.747860,-88.023980,Entire home/apt,141,3,250,2/23/2021,2.00,5,225
1,36690,Mo's Cozy Cabana w/ comfy veranda & access to ...,157752,Monique,Belize,Belize Islands,17.748320,-88.024740,Entire home/apt,71,3,316,2/19/2021,2.46,5,164
2,108932,Purple House eco solar w/ ocean & wildlife views,563377,Michael,Belize,Belize Islands,17.732210,-88.038240,Entire home/apt,191,2,30,3/14/2020,0.78,1,364
3,110483,Michelo's fuchsia suite,567809,Michel,Stann Creek,Stann Creek Mainland,16.521140,-88.369260,Hotel room,121,1,27,2/24/2020,0.29,3,331
4,120115,Seaside Villas Second Floor Unit #4,604999,Bobbi,Belize,Belize Islands,17.741660,-88.023950,Entire home/apt,343,1,30,3/18/2020,0.64,22,203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2791,48283996,Magical Island,17994012,Ronald,Belize,Belize Islands,17.945690,-87.944620,Entire home/apt,1054,3,0,NaN,NaN,2,347
2792,48287613,"The Luxury Suite - Corozal, Bz- 3Bdr/2bthr CASA1",375769845,Michael,Corozal,Corozal,18.374630,-88.400190,Entire home/apt,401,3,0,NaN,NaN,2,302
2793,48296096,Lagoon front apartment w/shared pool - two mi...,76414486,Vacasa Belize,Belize,Belize Islands,17.934580,-87.955220,Entire home/apt,252,1,0,NaN,NaN,204,364
2794,48296978,Beachfront Poolside Condo,15308338,Alexandra,Belize,Belize Islands,17.930010,-87.957120,Entire home/apt,242,3,0,NaN,NaN,4,364
2795,48332221,Standard Room - San Ignacio Resort Hotel,60399527,San Ignacio,Cayo,Cayo,17.154127,-89.069689,Private room,226,1,0,NaN,NaN,5,365

In [87]:
neighbourhood = df1['neighbourhood_group'].unique()
df = pd.DataFrame.from_dict({'neighbourhood_group': ['Belize', 'Stann Creek', 'Toledo', 'Cayo','Corozal','Orange Walk']})
df

  neighbourhood_group
0              Belize
1         Stann Creek
2              Toledo
3                Cayo
4             Corozal
5         Orange Walk

In [30]:
merged = pd.concat([df1,dummies],axis = "columns")
merged

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,Belize,Cayo,Corozal,Orange Walk,Stann Creek,Toledo
0,36666,Mo's Cozy Casa w/ veranda & access to dock,157752,Monique,Belize,Belize Islands,17.747860,-88.023980,Entire home/apt,141,...,2/23/2021,2.00,5,225,1,0,0,0,0,0
1,36690,Mo's Cozy Cabana w/ comfy veranda & access to ...,157752,Monique,Belize,Belize Islands,17.748320,-88.024740,Entire home/apt,71,...,2/19/2021,2.46,5,164,1,0,0,0,0,0
2,108932,Purple House eco solar w/ ocean & wildlife views,563377,Michael,Belize,Belize Islands,17.732210,-88.038240,Entire home/apt,191,...,3/14/2020,0.78,1,364,1,0,0,0,0,0
3,110483,Michelo's fuchsia suite,567809,Michel,Stann Creek,Stann Creek Mainland,16.521140,-88.369260,Hotel room,121,...,2/24/2020,0.29,3,331,0,0,0,0,1,0
4,120115,Seaside Villas Second Floor Unit #4,604999,Bobbi,Belize,Belize Islands,17.741660,-88.023950,Entire home/apt,343,...,3/18/2020,0.64,22,203,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2791,48283996,Magical Island,17994012,Ronald,Belize,Belize Islands,17.945690,-87.944620,Entire home/apt,1054,...,NaN,NaN,2,347,1,0,0,0,0,0
2792,48287613,"The Luxury Suite - Corozal, Bz- 3Bdr/2bthr CASA1",375769845,Michael,Corozal,Corozal,18.374630,-88.400190,Entire home/apt,401,...,NaN,NaN,2,302,0,0,1,0,0,0
2793,48296096,Lagoon front apartment w/shared pool - two mi...,76414486,Vacasa Belize,Belize,Belize Islands,17.934580,-87.955220,Entire home/apt,252,...,NaN,NaN,204,364,1,0,0,0,0,0
2794,48296978,Beachfront Poolside Condo,15308338,Alexandra,Belize,Belize Islands,17.930010,-87.957120,Entire home/apt,242,...,NaN,NaN,4,364,1,0,0,0,0,0
2795,48332221,Standard Room - San Ignacio Resort Hotel,60399527,San Ignacio,Cayo,Cayo,17.154127,-89.069689,Private room,226,...,NaN,NaN,5,365,0,1,0,0,0,0

In [33]:
final = merged.drop(['neighbourhood_group'],axis ='columns')
final

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,Belize,Cayo,Corozal,Orange Walk,Stann Creek,Toledo
0,36666,Mo's Cozy Casa w/ veranda & access to dock,157752,Monique,Belize Islands,17.747860,-88.023980,Entire home/apt,141,3,...,2/23/2021,2.00,5,225,1,0,0,0,0,0
1,36690,Mo's Cozy Cabana w/ comfy veranda & access to ...,157752,Monique,Belize Islands,17.748320,-88.024740,Entire home/apt,71,3,...,2/19/2021,2.46,5,164,1,0,0,0,0,0
2,108932,Purple House eco solar w/ ocean & wildlife views,563377,Michael,Belize Islands,17.732210,-88.038240,Entire home/apt,191,2,...,3/14/2020,0.78,1,364,1,0,0,0,0,0
3,110483,Michelo's fuchsia suite,567809,Michel,Stann Creek Mainland,16.521140,-88.369260,Hotel room,121,1,...,2/24/2020,0.29,3,331,0,0,0,0,1,0
4,120115,Seaside Villas Second Floor Unit #4,604999,Bobbi,Belize Islands,17.741660,-88.023950,Entire home/apt,343,1,...,3/18/2020,0.64,22,203,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2791,48283996,Magical Island,17994012,Ronald,Belize Islands,17.945690,-87.944620,Entire home/apt,1054,3,...,NaN,NaN,2,347,1,0,0,0,0,0
2792,48287613,"The Luxury Suite - Corozal, Bz- 3Bdr/2bthr CASA1",375769845,Michael,Corozal,18.374630,-88.400190,Entire home/apt,401,3,...,NaN,NaN,2,302,0,0,1,0,0,0
2793,48296096,Lagoon front apartment w/shared pool - two mi...,76414486,Vacasa Belize,Belize Islands,17.934580,-87.955220,Entire home/apt,252,1,...,NaN,NaN,204,364,1,0,0,0,0,0
2794,48296978,Beachfront Poolside Condo,15308338,Alexandra,Belize Islands,17.930010,-87.957120,Entire home/apt,242,3,...,NaN,NaN,4,364,1,0,0,0,0,0
2795,48332221,Standard Room - San Ignacio Resort Hotel,60399527,San Ignacio,Cayo,17.154127,-89.069689,Private room,226,1,...,NaN,NaN,5,365,0,1,0,0,0,0

In [23]:
u =[2,3,1]
v =[0,5,4]

def cross_product(u,v):
    qi = u[1]*v[2]-u[2]*v[1]
    qj = u[2]*v[0]-u[0]*v[2]
    qk = u[0]*v[1]-u[1]*v[0]
    q = [qi,qj,qk]

    return q


cross_product(u,v)

[7, -8, 10]

In [25]:
A = [2,4,3]
B = [6,5,1]
dotProduct = 0
for i in range(len(A)):
    try:
    
    value = A[i]*B[i]
    dotProduct+=value
    print(dotProduct)

12
32
35

In [ ]:
Machine learning algorithms cannot work with categorical data directly.

Categorical data must be converted to numbers.and this is call one hot encodding